config/routes.rb
SponsorpayOfferApi::Application.routes.draw do
  root :to => "offers#home" 
  resources :offers, only: :index
end

app/models/offer.rb
require 'sponsorpay'  #/lib 

class Offer 

  #---FIELDS to be displayed to the user
  @fields_hash = {uid: true, pub0: false, page: false}
  
  def self.fields 
    keys ||= @fields_hash.keys
  end

  def self.mandatory?(field)
    @fields_hash[field]
  end

  #---
  def initialize(hashie)
    @offer_data = hashie
    self
  end

  #each Offer delegates to the hashie provided by the API (/lib)
  def method_missing(method, *args)
    return super unless @offer_data.respond_to?(method)
    @offer_data.send(method, *args)
  end

  attr_accessor :error_message

  #---
  #fetch Offers from SponsorPay and return an array of them.
  def self.fetch_offers(params={})
    if validate_presence params
      strip params
      begin
        fetched = SponsorPay.offers params[:uid], params.symbolize_keys
      rescue SponsorPay::SponsorPayError => e
        response = Offer.new(nil)
        response.error_message = e.message
      end
    else
      response = Offer.new(nil)
      response.error_message = 'One or more mandatory keys are missing'
    end
    response ||= fetched.offers.each_with_object([]) { |offer, ary| ary << Offer.new(offer) }
  end

  private 
  def self.validate_presence(params)
    params.delete_if { |key, value| !fields.include?(key.to_sym) || value.blank? }
    fields.each { |f| return false if mandatory?(f) && !params.include?(f) }
  end

  def self.strip(params)
    params.each_key { |key| params[key].strip! }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
  def home 
    @fields = Offer.fields 
  end

  def index
    @offers = Offer.fetch_offers(params)
    respond_to do |format|
      format.js { render :index }
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SponsorpayOfferApi</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/offers/_offers.html.erb
<% if @offers.respond_to? :error_message %>
  <div class="alert alert-danger">
    <p> <%= @offers.error_message %> </p>
  </div>

<% elsif @offers.empty? %>
  <div class="alert alert-info">
    No offers 
  </div>

<% else %> 
  <div class="offers">
  <% @offers.each do |offer| %> 
    <div class="offer">
      <div class="title"><%= offer.title %> </div>
      <div class="payout"><%= offer.payout %> </div>
      <div class="thumbnail"> <%= image_tag offer.thumbnail.lowres, :alt => "offer thumbnail" %> </div>
    </div>
  <% end %> 
  </div>

<% end %> 

app/views/offers/home.html.erb
<div>
  <%= form_tag(offers_path, method: :get, :class => "", id:'parameters', remote: true) do %>

    <% @fields.each do |field| %>
      <div class="form-group">
        <% if Offer.mandatory? field %>
          <span class="label label-info"> Mandatory </span>
        <% end %>
        <%= text_field_tag(field, '', :class => "", :placeholder => field) %>
      </div>
    <% end %>

    <%= submit_tag "Get offers", :class => "", 'data-disable-with' => "Fetching..." %>
  <% end %>
</div>

<div id="container-offers">
  <!-- ajax:success will put the response here -->
</div>

app/views/offers/index.html.erb
<% if @offers.nil? %>
  <div class="alert alert-danger">
    Mandatory parameters are required.
  </div>

<% elsif @offers.empty? %>
  <div class="alert alert-info">
    No offers 
  </div>

<% else %> 
  <div class="">
  <% @offers.each do |offer| %> 
    <div class="offer">
      <div class="title"><%= offer.title %> </div>
      <div class="title"><%= offer.payout %> </div>
      <div class="title"><%= offer.thumbnail.lowres %> </div>
    </div>
  <% end %> 
  </div>

<% end %> 

app/views/offers/index.js.erb
$("#container-offers").html("<%= escape_javascript(render('offers')) %>");